In [2]:
a=4
b=5
c=a+b
print(c)

9


In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr = np.array([34,13,76,33,89])
max_value = np.max(arr)
min_value = np.min(arr)
print("Max:", max_value)
print("Min:", min_value)

Max: 89
Min: 13


In [6]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [7]:
x = np.array([1, 2])  
print(x.dtype)         


int32


In [8]:
arr = np.array([7, 6, 2, 3, 8])
mean = np.mean(arr)
std_dev = np.std(arr)
print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 5.2
Standard Deviation: 2.3151673805580453


In [9]:
arr3 = np.arange(12)
reshaped_arr = arr3.reshape(3,4) 

In [10]:
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
reshaped_arr = arr3.reshape(3,4) 
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
concatenated = np.concatenate((arr_a, arr_b))
print("Concatenated:", concatenated)

Concatenated: [1 2 3 4 5 6]
